import type {Metadata} from "next";
import "./globals.css";
import QueryProvider from "@/providers/QueryProvider";
import "bootstrap/dist/css/bootstrap.min.css"; //
import BootstrapClient from "@/components/BootstrapClient";
import {Great_Vibes, Poppins} from "next/font/google";

// Настраиваем Poppins (основной шрифт)
const poppins = Poppins({
    weight: ['400', '700'],
    subsets: ['latin', 'latin-ext'],
    variable: '--font-poppins', // Создаем CSS-переменную
});

// Настраиваем Great Vibes (декоративный)
const greatVibes = Great_Vibes({
    weight: '400',
    subsets: ['latin'],
    variable: '--font-great-vibes',
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {

    return (
        <html lang="en" className={`${poppins.variable} ${greatVibes.variable}`}>
        <QueryProvider>
            <body
                className="font-poppins"
            >
            {children}
            </body>
        </QueryProvider>
        <BootstrapClient />
        </html>
    );
}
